version: '2'

services:
    app:
      container_name: m1-app
      image: luckyraul/docker-dummy
      volumes:
        - ./application:/var/www
    php:
      container_name: m1-php
      image: mygento/php:5.6-full
      environment:
        - PHPFPM_USER=$USERID
      volumes_from:
       - app
      links:
       - redis
       - db
    redis:
      image: redis:3
      container_name: m1-redis
    nginx:
      container_name: m1-nginx
      image: luckyraul/nginx:backports
      environment:
        - NGINX_USER=$USERID
      ports:
       - 8081:80
      volumes:
        - ./conf/nginx:/etc/nginx/sites-enabled/
      volumes_from:
       - app
      depends_on:
       - php
    db:
      container_name: m1-db
      image: mygento/mysql
      command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --innodb_file_per_table
      ports:
       - 3306:3306
      environment:
       - MYSQL_ROOT_PASSWORD=mygento
       - MYSQL_DATABASE=magento
       - MYSQL_USER=mygento
       - MYSQL_PASSWORD=mygento
      volumes:
       - "m1-db-data:/var/lib/mysql"
volumes:
    m1-db-data:
