version: '2'

services:
    app:
      container_name: app
      build: ./application/.
      image: mageapp
      volumes:
        - ./application:/var/www/public
    php:
      container_name: php
      image: mygento/php:5.6-fpm
      volumes_from:
       - app
      links:
       - redis
       - db
      env:
        - ADMIN_USERNAME=admin
        - ADMIN_URL=backend
        - APPLICATION_MODE=development
    redis:
      image: redis:3
      container_name: redis
    nginx:
      container_name: nginx
      image: mygento/nginx:backports
      ports:
       - 8081:80
      volumes:
        - ./conf/nginx:/etc/nginx/sites-enabled/
      volumes_from:
       - app
      depends_on:
       - php
    db:
      container_name: db
      image: mygento/mysql
      environment:
       - MYSQL_ROOT_PASSWORD=mygento
       - MYSQL_DATABASE=magento
       - MYSQL_USER=mygento
       - MYSQL_PASSWORD=mygento
      volumes:
       - "db-data:/var/lib/mysql"
volumes:
    db-data:
