version: '2'

services:
    app:
      build: ./application/.
      image: mageapp
      volumes: 
        - /var/www
    php:
      image: mygento/php:5.6-fpm
      volumes_from: 
       - app
      links:
       - redis
       - db
    redis:
      image: redis
    nginx:
      image: mygento/nginx:backports
      ports:
       - 8081:80 
      volumes: 
        - ./conf/nginx:/etc/nginx/sites-enabled/
      volumes_from:
       - app
      depends_on:
       - php
    db:
      image: mygento/mysql
      environment:
       - MYSQL_ROOT_PASSWORD=mygento
       - MYSQL_DATABASE=magento
       - MYSQL_USER=mygento
       - MYSQL_PASSWORD=mygento
      volumes:
       - "db-data:/var/lib/mysql"
volumes:
    db-data:
    