version: "2"

services:
  web:
    container_name: nginx_magento
    image: mygento/nginx:backports
    volumes:
      - ./public:/var/www/magento
      - ./conf/nginx:/etc/nginx/sites-enabled
    ports:
      - "8080:80"
    networks:
      - magento
    depends_on:
      - php
  php:
    container_name: php_magento
    image: mygento/php:5.6
    volumes:
      - ./public:/var/www/magento
    networks:
      - magento
  db:
    container_name: mysql_magento
    image: mygento/mysql
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mygento
    networks:
      - magento
volumes:
  db-data:

networks:
  magento: 
    driver: overlay
